In [38]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
%matplotlib inline

In [50]:
df = pd.read_csv('MLSStyle1 - Sheet1.csv')

In [51]:
df

,Squad,SoT,npxG/Sh,PPA,CrsPA,%Live,%Dead,%Drib,Att 3rd,Att Pen
0,Atlanta Utd,4.35,0.09,7.41,2.18,72.371416,8.284024,7.100592,150.4,21.9
1,Austin FC,4.29,0.10,9.41,2.47,73.915117,9.680496,5.484025,173.1,23.8
2,CF Montr√©al,3.76,0.11,8.00,1.79,73.569482,8.174387,6.430518,154.1,22.6
3,Chicago Fire,4.53,0.09,8.53,2.71,72.628234,12.165229,4.403087,152.5,23.4
4,Colorado Rapids,4.32,0.10,7.50,2.06,73.597056,8.371665,7.037718,147.0,23.4
5,Columbus Crew,3.94,0.10,6.97,1.91,70.550508,8.337787,5.505078,147.4,19.9
6,D.C. United,4.44,0.11,8.56,2.26,69.325736,10.066477,5.318139,144.0,23.4
7,FC Cincinnati,3.94,0.09,6.47,1.32,65.940055,9.918256,6.757493,125.0,20.1
8,FC Dallas,4.24,0.11,7.03,1.79,71.812408,8.744504,6.057645,135.0,21.4
9,Houston Dynamo,4.12,0.09,6.59,1.91,72.597137,8.895706,4.652352,147.8,20.7
10,Inter Miami,3.47,0.10,6.62,1.65,72.066327,9.948980,4.528061,132.9,16.6
11,LA Galaxy,4.26,0.11,8.94,2.47,76.663452,7.810993,5.400193,167.8,23.7
12,Los Angeles FC,5.09,0.11,10.90,1.65,70.811033,7.616303,6.916427,196.1,29.8
13,Minnesota Utd,4.09,0.10,8.68,2.44,70.937231,8.598452,6.835770,189.5,24.9
14,Nashville,5.21,0.10,7.26,2.24,67.990074,11.960298,4.069479,131.8,21.2
15,New England,5.03,0.11,10.90,3.15,73.981712,9.310058,6.234414,170.5,28.7
16,NY Red Bulls,4.00,0.09,8.44,2.53,66.884939,10.336763,7.156221,165.7,24.3
17,NYCFC,5.32,0.11,11.30,2.35,72.117400,9.853249,4.318658,172.7,29.6
18,Orlando City,4.00,0.10,8.00,1.91,72.517078,9.406201,3.993694,144.3,22.4
19,Philadelphia,4.29,0.11,10.30,2.91,73.339940,9.762141,5.104063,177.0,26.5
20,Portland Timbers,4.21,0.11,7.94,1.79,70.908208,11.413307,5.730937,149.7,22.2
21,Real Salt Lake,5.00,0.10,8.00,2.74,74.231679,10.023641,4.302600,147.0,22.1
22,San Jose,4.62,0.10,6.74,2.03,68.083052,10.091743,6.228875,139.5,21.4
23,Seattle,4.35,0.10,7.09,2.21,68.217874,11.528292,4.336330,140.6,21.1
24,Sporting KC,4.79,0.11,8.62,2.47,75.408261,5.235351,5.091258,184.9,23.6
25,Toronto FC,3.68,0.11,8.56,1.56,75.288403,7.346691,7.346691,168.1,23.3
26,Vancouver,3.32,0.11,5.76,1.82,62.597911,14.621410,5.939948,131.5,18.4

In [52]:
features = ['SoT','npxG/Sh','PPA','CrsPA','%Live','%Dead','%Drib','Att 3rd','Att Pen']
x = df.loc[:, features].values

In [53]:
x = StandardScaler().fit_transform(x)

In [54]:
pd.DataFrame(data = x, columns = features).head()

,SoT,npxG/Sh,PPA,CrsPA,%Live,%Dead,%Drib,Att 3rd,Att Pen
0,0.058394,-1.679140,-0.536157,0.046168,0.303148,-0.701117,1.382200,-0.247735,-0.359654
1,-0.061351,-0.345705,0.879613,0.715596,0.795241,0.080216,-0.147614,0.965988,0.274375
2,-1.119098,0.987730,-0.118505,-0.854099,0.685061,-0.762460,0.748085,-0.049903,-0.126064
3,0.417629,-1.679140,0.256674,1.269606,0.385016,1.470438,-1.170544,-0.135452,0.140895
4,-0.001478,-0.345705,-0.472448,-0.230838,0.693851,-0.652082,1.322701,-0.429526,0.140895

In [55]:
pca = PCA(n_components=2)

In [56]:
principalComponents = pca.fit_transform(x)

In [57]:
principalDf = pd.DataFrame(data = principalComponents
             , columns = ['principal component 1', 'principal component 2'])

In [58]:
principalDf

    principal component 1  principal component 2
0                0.532696               0.954809
1               -1.287698              -0.227010
2                0.074984               1.864875
3                0.038996              -2.306962
4                0.055524               1.213246
5                1.425386               0.762329
6                0.004526              -0.638281
7                3.422908               0.978754
8                0.988072               0.924622
9                1.496502              -0.036078
10               2.943084               0.432286
11              -1.816065               0.570621
12              -3.471508               1.344242
13              -1.341300               1.001999
14               1.315184              -2.674443
15              -3.735567              -0.988947
16               0.316482               0.081216
17              -3.378794              -1.724438
18               0.743670              -0.414518
19              -2.579040              -0.813475
20               0.738745               0.048978
21              -0.537307              -1.907811
22               1.443118              -0.212162
23               1.641445              -1.599356
24              -2.658919               0.816736
25              -0.652732               3.066075
26               4.277610              -0.517308

In [59]:
principalDf['Euc Dist'] = np.sqrt(((principalDf['principal component 1']-1.443118)**2)+((principalDf['principal component 2']+0.212162)**2))

In [60]:
principalDf

    principal component 1  principal component 2      Euc Dist
0                0.532696               0.954809  1.480098e+00
1               -1.287698              -0.227010  2.730856e+00
2                0.074984               1.864875  2.487142e+00
3                0.038996              -2.306962  2.521854e+00
4                0.055524               1.213246  1.989273e+00
5                1.425386               0.762329  9.746525e-01
6                0.004526              -0.638281  1.500375e+00
7                3.422908               0.978754  2.310379e+00
8                0.988072               0.924622  1.224477e+00
9                1.496502              -0.036078  1.839983e-01
10               2.943084               0.432286  1.632547e+00
11              -1.816065               0.570621  3.351869e+00
12              -3.471508               1.344242  5.155186e+00
13              -1.341300               1.001999  3.037626e+00
14               1.315184              -2.674443  2.465602e+00
15              -3.735567              -0.988947  5.236619e+00
16               0.316482               0.081216  1.164208e+00
17              -3.378794              -1.724438  5.053495e+00
18               0.743670              -0.414518  7.281316e-01
19              -2.579040              -0.813475  4.066857e+00
20               0.738745               0.048978  7.512227e-01
21              -0.537307              -1.907811  2.607164e+00
22               1.443118              -0.212162  2.710295e-07
23               1.641445              -1.599356  1.401299e+00
24              -2.658919               0.816736  4.229106e+00
25              -0.652732               3.066075  3.890942e+00
26               4.277610              -0.517308  2.850870e+00

In [61]:
teams = df['Squad']
principalDf = principalDf.join(teams)

In [62]:
principalDf

,principal component 1,principal component 2,Euc Dist,Squad
0,0.532696,0.954809,1.480098e+00,Atlanta Utd
1,-1.287698,-0.227010,2.730856e+00,Austin FC
2,0.074984,1.864875,2.487142e+00,CF Montr√©al
3,0.038996,-2.306962,2.521854e+00,Chicago Fire
4,0.055524,1.213246,1.989273e+00,Colorado Rapids
5,1.425386,0.762329,9.746525e-01,Columbus Crew
6,0.004526,-0.638281,1.500375e+00,D.C. United
7,3.422908,0.978754,2.310379e+00,FC Cincinnati
8,0.988072,0.924622,1.224477e+00,FC Dallas
9,1.496502,-0.036078,1.839983e-01,Houston Dynamo
10,2.943084,0.432286,1.632547e+00,Inter Miami
11,-1.816065,0.570621,3.351869e+00,LA Galaxy
12,-3.471508,1.344242,5.155186e+00,Los Angeles FC
13,-1.341300,1.001999,3.037626e+00,Minnesota Utd
14,1.315184,-2.674443,2.465602e+00,Nashville
15,-3.735567,-0.988947,5.236619e+00,New England
16,0.316482,0.081216,1.164208e+00,NY Red Bulls
17,-3.378794,-1.724438,5.053495e+00,NYCFC
18,0.743670,-0.414518,7.281316e-01,Orlando City
19,-2.579040,-0.813475,4.066857e+00,Philadelphia
20,0.738745,0.048978,7.512227e-01,Portland Timbers
21,-0.537307,-1.907811,2.607164e+00,Real Salt Lake
22,1.443118,-0.212162,2.710295e-07,San Jose
23,1.641445,-1.599356,1.401299e+00,Seattle
24,-2.658919,0.816736,4.229106e+00,Sporting KC
25,-0.652732,3.066075,3.890942e+00,Toronto FC
26,4.277610,-0.517308,2.850870e+00,Vancouver

In [65]:
principalDf.sort_values(by=['Euc Dist'], inplace=True, ascending=False)

In [66]:
principalDf

,principal component 1,principal component 2,Euc Dist,Squad
15,-3.735567,-0.988947,5.236619e+00,New England
12,-3.471508,1.344242,5.155186e+00,Los Angeles FC
17,-3.378794,-1.724438,5.053495e+00,NYCFC
24,-2.658919,0.816736,4.229106e+00,Sporting KC
19,-2.579040,-0.813475,4.066857e+00,Philadelphia
25,-0.652732,3.066075,3.890942e+00,Toronto FC
11,-1.816065,0.570621,3.351869e+00,LA Galaxy
13,-1.341300,1.001999,3.037626e+00,Minnesota Utd
26,4.277610,-0.517308,2.850870e+00,Vancouver
1,-1.287698,-0.227010,2.730856e+00,Austin FC
21,-0.537307,-1.907811,2.607164e+00,Real Salt Lake
3,0.038996,-2.306962,2.521854e+00,Chicago Fire
2,0.074984,1.864875,2.487142e+00,CF Montr√©al
14,1.315184,-2.674443,2.465602e+00,Nashville
7,3.422908,0.978754,2.310379e+00,FC Cincinnati
4,0.055524,1.213246,1.989273e+00,Colorado Rapids
10,2.943084,0.432286,1.632547e+00,Inter Miami
6,0.004526,-0.638281,1.500375e+00,D.C. United
0,0.532696,0.954809,1.480098e+00,Atlanta Utd
23,1.641445,-1.599356,1.401299e+00,Seattle
8,0.988072,0.924622,1.224477e+00,FC Dallas
16,0.316482,0.081216,1.164208e+00,NY Red Bulls
5,1.425386,0.762329,9.746525e-01,Columbus Crew
20,0.738745,0.048978,7.512227e-01,Portland Timbers
18,0.743670,-0.414518,7.281316e-01,Orlando City
9,1.496502,-0.036078,1.839983e-01,Houston Dynamo
22,1.443118,-0.212162,2.710295e-07,San Jose

In [ ]:
#Most similar Attacking
#Houston,Orlando,Portland,Columbus,NYRB

In [67]:
df = pd.read_csv('MLSStyle - Sheet2.csv')

In [68]:
df

,Squad,Cmp,Cmp%,PrgDist,%Long,Final 3rd,TB,Sw,Poss,Def Pen,Def 3rd,Mid 3rd,PrgDist.1,%ProgPassing
0,Atlanta Utd,452.3,84.6,2698.5,20.321856,28.6,1.03,19.70,57.4,73.5,234.6,307.4,1291.4,67.633274
1,Austin FC,432.5,84.0,2811.4,19.569016,33.4,0.76,17.30,54.0,80.1,231.6,262.8,1182.3,70.395873
2,CF Montr√©al,432.3,83.9,2799.7,17.569404,33.0,1.09,14.30,52.9,64.6,212.8,300.5,1170.2,70.523187
3,Chicago Fire,367.7,78.8,2597.8,19.644387,26.0,0.76,13.50,49.8,68.0,196.6,280.0,944.6,73.334463
4,Colorado Rapids,383.9,82.1,2703.3,21.509515,32.1,1.21,16.50,48.3,63.4,198.6,262.9,1015.0,72.702579
5,Columbus Crew,397.6,81.8,2761.2,22.290767,30.5,0.74,15.90,51.7,73.1,214.3,270.6,941.3,74.576637
6,D.C. United,312.0,75.4,2450.9,24.202128,25.6,0.88,13.60,46.0,56.7,172.9,257.5,868.9,73.826737
7,FC Cincinnati,384.1,82.8,2403.5,19.780220,24.1,1.21,16.40,49.0,73.1,234.1,263.6,1033.3,69.934241
8,FC Dallas,406.4,82.1,2612.5,20.189784,27.2,1.03,15.60,51.1,80.7,245.5,270.4,1106.7,70.243601
9,Houston Dynamo,328.9,77.8,2333.5,22.072392,27.8,0.97,14.70,45.1,58.8,187.1,237.7,944.3,71.191043
10,Inter Miami,368.9,82.1,2567.1,21.388827,28.6,1.09,17.50,46.2,64.9,190.6,267.5,932.4,73.356194
11,LA Galaxy,461.6,84.2,2852.3,17.563378,31.6,1.09,15.20,54.3,71.8,226.3,311.1,1255.9,69.429434
12,Los Angeles FC,374.7,79.7,2598.7,17.769738,32.5,1.18,10.10,49.8,52.1,177.9,271.3,1025.6,71.702122
13,Minnesota Utd,389.1,80.2,2755.7,19.377448,34.4,0.71,14.00,50.1,56.6,174.9,278.0,988.2,73.605064
14,Nashville,362.9,80.2,2652.9,23.236790,27.4,0.68,14.00,46.5,59.7,190.1,269.9,894.6,74.782241
15,New England,388.8,80.8,2881.0,21.517671,32.7,0.88,15.30,50.9,60.9,184.6,287.9,1088.6,72.576582
16,NY Red Bulls,291.9,71.2,2301.3,24.701292,28.3,0.50,12.00,48.1,51.3,169.5,248.3,853.1,72.955237
17,NYCFC,408.2,81.2,2842.3,17.963000,30.5,1.09,13.00,53.5,61.5,200.4,290.9,1086.9,72.337881
18,Orlando City,409.7,83.5,2753.1,18.732165,29.2,0.85,14.10,51.1,63.5,209.9,287.3,981.6,73.716764
19,Philadelphia,339.8,76.8,2608.6,23.961156,29.7,0.74,19.00,48.2,58.6,175.1,243.2,996.3,72.362617
20,Portland Timbers,358.0,80.4,2635.2,20.570402,28.9,0.97,12.70,44.9,73.1,207.3,245.1,1031.2,71.874318
21,Real Salt Lake,373.2,80.3,2698.8,22.901421,29.1,0.91,17.60,50.9,65.0,200.2,269.3,1024.4,72.486033
22,San Jose,377.0,81.1,2549.3,24.290017,25.9,0.53,20.60,52.6,72.2,223.1,263.4,1109.8,69.670137
23,Seattle,381.2,79.7,2632.1,20.547659,27.4,0.41,13.20,48.6,69.9,219.9,269.6,947.4,73.532616
24,Sporting KC,473.5,84.3,2838.5,20.946788,38.0,0.91,22.70,55.0,65.8,218.6,321.8,1361.4,67.584943
25,Toronto FC,412.4,82.0,2581.3,16.322068,31.5,0.91,9.32,49.4,66.0,193.8,288.7,1033.5,71.409207
26,Vancouver,350.4,79.5,2503.2,23.621511,25.9,0.79,15.20,46.1,66.0,198.6,254.4,895.6,73.649523

In [69]:
features = ['Cmp','Cmp%','PrgDist','%Long','Final 3rd','TB','Sw','Poss','Def Pen','Def 3rd','Mid 3rd','PrgDist.1','%ProgPassing']
x = df.loc[:, features].values

In [70]:
x = StandardScaler().fit_transform(x)

In [71]:
pd.DataFrame(data = x, columns = features).head()

,Cmp,Cmp%,PrgDist,%Long,Final 3rd,TB,Sw,Poss,Def Pen,Def 3rd,Mid 3rd,PrgDist.1,%ProgPassing
0,1.579459,1.308372,0.347886,-0.224345,-0.328745,0.688922,1.490493,2.324297,1.060318,1.505883,1.655034,2.019953,-2.244682
1,1.108554,1.103978,1.086473,-0.553109,1.209356,-0.602143,0.678044,1.248299,1.944909,1.361584,-0.514327,1.152997,-0.792473
2,1.103798,1.069913,1.009932,-1.426336,1.081181,0.975825,-0.337517,0.900182,-0.132540,0.457305,1.319415,1.056846,-0.725548
3,-0.432587,-0.667434,-0.310888,-0.520194,-1.161884,-0.602143,-0.608334,-0.080876,0.323159,-0.321913,0.322288,-0.735869,0.752249
4,-0.047302,0.456732,0.379288,0.294304,0.792787,1.549632,0.407228,-0.555581,-0.293374,-0.225713,-0.509463,-0.176440,0.420088

In [72]:
pca = PCA(n_components=2)

In [73]:
principalComponents = pca.fit_transform(x)

In [74]:
principalDf = pd.DataFrame(data = principalComponents
             , columns = ['principal component 1', 'principal component 2'])

In [75]:
principalDf

    principal component 1  principal component 2
0               -4.703369               1.662269
1               -3.156309               1.082936
2               -3.065992              -1.510085
3                1.192747              -0.016361
4                0.008100              -0.592437
5               -0.112267               0.446082
6                4.395891               0.010295
7               -0.457626               2.252412
8               -1.799365               2.123664
9                3.249581               0.594435
10               1.173232               0.108508
11              -4.506557              -0.615010
12               0.677076              -2.931148
13               0.519721              -2.423840
14               2.441649              -0.274476
15              -0.558101              -1.541696
16               5.605906              -0.139693
17              -1.509479              -1.897662
18              -0.739317              -0.966629
19               2.545250               0.498958
20               1.107212               0.511001
21               0.318919               0.493051
22              -0.325996               3.353821
23               1.109122               0.738661
24              -5.482228              -0.147887
25              -0.637655              -1.973181
26               2.709854               1.154010

In [76]:
principalDf['Euc Dist'] = np.sqrt(((principalDf['principal component 1']+0.325996)**2)+((principalDf['principal component 2']-3.353821)**2))

In [77]:
principalDf

    principal component 1  principal component 2      Euc Dist
0               -4.703369               1.662269  4.692840e+00
1               -3.156309               1.082936  3.628717e+00
2               -3.065992              -1.510085  5.582577e+00
3                1.192747              -0.016361  3.696580e+00
4                0.008100              -0.592437  3.960375e+00
5               -0.112267               0.446082  2.915583e+00
6                4.395891               0.010295  5.785791e+00
7               -0.457626               2.252412  1.109247e+00
8               -1.799365               2.123664  1.919401e+00
9                3.249581               0.594435  4.516521e+00
10               1.173232               0.108508  3.574876e+00
11              -4.506557              -0.615010  5.764435e+00
12               0.677076              -2.931148  6.364510e+00
13               0.519721              -2.423840  5.839229e+00
14               2.441649              -0.274476  4.563376e+00
15              -0.558101              -1.541696  4.901016e+00
16               5.605906              -0.139693  6.884192e+00
17              -1.509479              -1.897662  5.383187e+00
18              -0.739317              -0.966629  4.340176e+00
19               2.545250               0.498958  4.048987e+00
20               1.107212               0.511001  3.183663e+00
21               0.318919               0.493051  2.932562e+00
22              -0.325996               3.353821  5.938024e-07
23               1.109122               0.738661  2.983056e+00
24              -5.482228              -0.147887  6.232872e+00
25              -0.637655              -1.973181  5.336111e+00
26               2.709854               1.154010  3.749074e+00

In [78]:
teams = df['Squad']
principalDf = principalDf.join(teams)

In [79]:
principalDf.head()

   principal component 1  principal component 2  Euc Dist            Squad
0              -4.703369               1.662269  4.692840      Atlanta Utd
1              -3.156309               1.082936  3.628717        Austin FC
2              -3.065992              -1.510085  5.582577      CF Montr√©al
3               1.192747              -0.016361  3.696580     Chicago Fire
4               0.008100              -0.592437  3.960375  Colorado Rapids

In [80]:
principalDf.sort_values(by=['Euc Dist'], inplace=True, ascending=False)

In [81]:
principalDf

,principal component 1,principal component 2,Euc Dist,Squad
16,5.605906,-0.139693,6.884192e+00,NY Red Bulls
12,0.677076,-2.931148,6.364510e+00,Los Angeles FC
24,-5.482228,-0.147887,6.232872e+00,Sporting KC
13,0.519721,-2.423840,5.839229e+00,Minnesota Utd
6,4.395891,0.010295,5.785791e+00,D.C. United
11,-4.506557,-0.615010,5.764435e+00,LA Galaxy
2,-3.065992,-1.510085,5.582577e+00,CF Montr√©al
17,-1.509479,-1.897662,5.383187e+00,NYCFC
25,-0.637655,-1.973181,5.336111e+00,Toronto FC
15,-0.558101,-1.541696,4.901016e+00,New England
0,-4.703369,1.662269,4.692840e+00,Atlanta Utd
14,2.441649,-0.274476,4.563376e+00,Nashville
9,3.249581,0.594435,4.516521e+00,Houston Dynamo
18,-0.739317,-0.966629,4.340176e+00,Orlando City
19,2.545250,0.498958,4.048987e+00,Philadelphia
4,0.008100,-0.592437,3.960375e+00,Colorado Rapids
26,2.709854,1.154010,3.749074e+00,Vancouver
3,1.192747,-0.016361,3.696580e+00,Chicago Fire
1,-3.156309,1.082936,3.628717e+00,Austin FC
10,1.173232,0.108508,3.574876e+00,Inter Miami
20,1.107212,0.511001,3.183663e+00,Portland Timbers
23,1.109122,0.738661,2.983056e+00,Seattle
21,0.318919,0.493051,2.932562e+00,Real Salt Lake
5,-0.112267,0.446082,2.915583e+00,Columbus Crew
8,-1.799365,2.123664,1.919401e+00,FC Dallas
7,-0.457626,2.252412,1.109247e+00,FC Cincinnati
22,-0.325996,3.353821,5.938024e-07,San Jose

In [ ]:
#Most similar in possession
#Cincinnati,Dallas,Columbus,RSL,Seattle

In [82]:
df = pd.read_csv('MLSStyle - Sheet3.csv')

In [83]:
df.head()

,Squad,%,Padj Def 3rd,Padj Mid 3rd,Padj Final 3rd,Padj Def 3rd.1,Padj Middle 3rd,Padj Final 3rd.1,%Def 3rd,%Mid 3rd,%fin 3rd,%Def 3rd.1,%mid 3rd,%final 3rd
0,Atlanta Utd,28.4,15.883843,12.492691,3.040343,101.929448,120.054570,52.231534,50.621118,39.813665,9.689441,37.171286,43.781095,19.047619
1,Austin FC,28.0,16.994763,8.867618,4.298357,95.358497,101.137800,63.933538,56.347305,29.401198,14.251497,36.615811,38.834952,24.549237
2,CF Montr√©al,28.9,12.283113,9.139323,3.229686,78.165264,110.462120,63.562962,49.652778,36.944444,13.055556,30.994550,43.801090,25.204360
3,Chicago Fire,31.4,14.541161,13.545884,4.419703,76.923077,105.937922,56.680162,44.663212,41.606218,13.575130,32.112676,44.225352,23.661972
4,Colorado Rapids,25.3,12.259970,9.420647,3.676350,73.362875,114.065321,55.309371,48.506493,37.272727,14.545455,30.223124,46.991210,22.785666

In [84]:
features = ['%','Padj Def 3rd','Padj Mid 3rd','Padj Final 3rd','Padj Def 3rd.1','Padj Middle 3rd','Padj Final 3rd.1','%Def 3rd','%Mid 3rd','%fin 3rd','%Def 3rd.1','%mid 3rd','%final 3rd']
x = df.loc[:, features].values

In [85]:
x = StandardScaler().fit_transform(x)

In [86]:
pd.DataFrame(data = x, columns = features).head()

,%,Padj Def 3rd,Padj Mid 3rd,Padj Final 3rd,Padj Def 3rd.1,Padj Middle 3rd,Padj Final 3rd.1,%Def 3rd,%Mid 3rd,%fin 3rd,%Def 3rd.1,%mid 3rd,%final 3rd
0,-0.254621,0.505765,0.809170,-1.159673,1.731954,0.613997,-0.814490,0.210762,0.940865,-1.633611,1.077350,0.238670,-1.509212
1,-0.493742,1.159368,-1.430780,0.320785,0.922478,-1.129379,0.345614,1.642199,-2.444685,0.438555,0.905824,-2.215857,0.580726
2,0.044282,-1.612706,-1.262892,-0.936850,-1.195556,-0.270047,0.308876,-0.031305,0.007955,-0.104662,-0.829982,0.248593,0.829592
3,1.538794,-0.284195,1.459943,0.463589,-1.348581,-0.686998,-0.373466,-1.278601,1.523703,0.131337,-0.484712,0.459133,0.243675
4,-2.107815,-1.626322,-1.089061,-0.411206,-1.787162,0.062026,-0.509362,-0.317854,0.114695,0.572076,-1.068193,1.831693,-0.089214

In [87]:
pca = PCA(n_components=2)

In [88]:
principalComponents = pca.fit_transform(x)

In [89]:
principalDf = pd.DataFrame(data = principalComponents
             , columns = ['principal component 1', 'principal component 2'])

In [90]:
principalDf

    principal component 1  principal component 2
0               -1.854184              -1.507172
1               -2.625123              -0.714512
2                0.546031               2.362336
3                2.129064               0.166473
4                0.620396               3.522057
5               -1.105335               0.704255
6                1.380510              -0.221250
7               -2.788088              -1.660229
8               -2.007127              -1.347874
9               -0.251726               1.905918
10              -1.788364               0.121798
11              -0.930610               0.710576
12               3.044570              -2.125294
13               2.418032              -0.135495
14              -0.821557               1.490690
15               0.488359              -0.086613
16               6.753107              -2.636520
17               4.613218               0.530354
18              -2.283933               0.233235
19               1.492466              -1.545711
20              -5.084529              -0.042566
21              -1.216034               0.477038
22              -1.354919              -2.882028
23              -2.893222              -1.989084
24               3.991359               1.064232
25              -0.027025               2.231636
26              -0.445335               1.373752

In [91]:
principalDf['Euc Dist'] = np.sqrt(((principalDf['principal component 1']+1.354919)**2)+((principalDf['principal component 2']+2.882028)**2))

In [92]:
principalDf

    principal component 1  principal component 2      Euc Dist
0               -1.854184              -1.507172  1.462701e+00
1               -2.625123              -0.714512  2.512279e+00
2                0.546031               2.362336  5.578258e+00
3                2.129064               0.166473  4.629416e+00
4                0.620396               3.522057  6.701804e+00
5               -1.105335               0.704255  3.594957e+00
6                1.380510              -0.221250  3.816060e+00
7               -2.788088              -1.660229  1.883286e+00
8               -2.007127              -1.347874  1.667034e+00
9               -0.251726               1.905918  4.913397e+00
10              -1.788364               0.121798  3.034937e+00
11              -0.930610               0.710576  3.617574e+00
12               3.044570              -2.125294  4.464096e+00
13               2.418032              -0.135495  4.666755e+00
14              -0.821557               1.490690  4.405126e+00
15               0.488359              -0.086613  3.348435e+00
16               6.753107              -2.636520  8.111742e+00
17               4.613218               0.530354  6.874810e+00
18              -2.283933               0.233235  3.250835e+00
19               1.492466              -1.545711  3.145369e+00
20              -5.084529              -0.042566  4.687487e+00
21              -1.216034               0.477038  3.361936e+00
22              -1.354919              -2.882028  4.607198e-07
23              -2.893222              -1.989084  1.778686e+00
24               3.991359               1.064232  6.644972e+00
25              -0.027025               2.231636  5.283262e+00
26              -0.445335               1.373752  4.351896e+00

In [93]:
teams = df['Squad']
principalDf = principalDf.join(teams)

In [94]:
principalDf.head()

   principal component 1  principal component 2  Euc Dist            Squad
0              -1.854184              -1.507172  1.462701      Atlanta Utd
1              -2.625123              -0.714512  2.512279        Austin FC
2               0.546031               2.362336  5.578258      CF Montr√©al
3               2.129064               0.166473  4.629416     Chicago Fire
4               0.620396               3.522057  6.701804  Colorado Rapids

In [95]:
principalDf.sort_values(by=['Euc Dist'], inplace=True, ascending=False)

In [97]:
principalDf

,principal component 1,principal component 2,Euc Dist,Squad
16,6.753107,-2.636520,8.111742e+00,NY Red Bulls
17,4.613218,0.530354,6.874810e+00,NYCFC
4,0.620396,3.522057,6.701804e+00,Colorado Rapids
24,3.991359,1.064232,6.644972e+00,Sporting KC
2,0.546031,2.362336,5.578258e+00,CF Montr√©al
25,-0.027025,2.231636,5.283262e+00,Toronto FC
9,-0.251726,1.905918,4.913397e+00,Houston Dynamo
20,-5.084529,-0.042566,4.687487e+00,Portland Timbers
13,2.418032,-0.135495,4.666755e+00,Minnesota Utd
3,2.129064,0.166473,4.629416e+00,Chicago Fire
12,3.044570,-2.125294,4.464096e+00,Los Angeles FC
14,-0.821557,1.490690,4.405126e+00,Nashville
26,-0.445335,1.373752,4.351896e+00,Vancouver
6,1.380510,-0.221250,3.816060e+00,D.C. United
11,-0.930610,0.710576,3.617574e+00,LA Galaxy
5,-1.105335,0.704255,3.594957e+00,Columbus Crew
21,-1.216034,0.477038,3.361936e+00,Real Salt Lake
15,0.488359,-0.086613,3.348435e+00,New England
18,-2.283933,0.233235,3.250835e+00,Orlando City
19,1.492466,-1.545711,3.145369e+00,Philadelphia
10,-1.788364,0.121798,3.034937e+00,Inter Miami
1,-2.625123,-0.714512,2.512279e+00,Austin FC
7,-2.788088,-1.660229,1.883286e+00,FC Cincinnati
23,-2.893222,-1.989084,1.778686e+00,Seattle
8,-2.007127,-1.347874,1.667034e+00,FC Dallas
0,-1.854184,-1.507172,1.462701e+00,Atlanta Utd
22,-1.354919,-2.882028,4.607198e-07,San Jose

In [ ]:
#Most similar Defensively
#Atlanta,Dallas,Seattle,Cincinnati,Austin